[package]
name = "vpratt-macros"
version = "0.5.1"
edition = "2024"
authors = ["synkibe@gmail.com"]
description = "Procedural macros for the vpratt pratt parsing framework."
repository = "https://github.com/syncbtx/vpratt"
license = "MIT"
keywords = ["parser", "pratt", "macro", "compiler", "ast",]
categories = ["development-tools::procedural-macro-helpers", "parsing"]

[lib]
proc-macro = true

[features]
trace = []

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
