[package]
name = "vpratt"
version = "0.1.1i"
edition = "2024"
authors = ["synkibe@gmail.com"]
description = "A zero-boilerplate framework for building mathematically correct, O(N) Pratt parsers."
repository = "https://github.com/syncbtx/vpratt"
homepage = "https://github.com/syncbtx/vpratt"
documentation = "https://doc.rs/vpratt"
license = "MIT "
readme = "../../README.md"
keywords = ["parser", "pratt", "expression", "compiler", "ast"]
categories = ["compilers","parsing", "no-std"]

[dependencies]
vpratt-macros = {path = "../vpratt-macros", version = "0.1.0"}

