[package]
name = "vpratt"
version = "0.6.1"
edition = "2024"
authors = ["synkibe@gmail.com"]
description = "absolute zenith of pratt parsing"
repository = "https://github.com/syncbtx/vpratt"
homepage = "https://github.com/syncbtx/vpratt"
documentation = "https://doc.rs/vpratt"
license = "MIT "
readme = "README.md"
keywords = ["parser", "pratt", "expression", "compiler", "ast"]
categories = ["compilers","parsing", "no-std"]

[features]
default = ["bp_u16"]
bp_u8 = []
bp_u16 = []

[dependencies]
vpratt-macros = {path = "../vpratt-macros", version = "0.6.0"}

